author: Anthony Phelps
database: false
main: me.aphelps.plugins.WhoNeedsWeather.WhoNeedsWeather
name: Who Needs Weather
startup: postworld
version: 0.0.1
commands:
   wr:
      description: Basic command for altering settings.
      permission: WhoNeedsWeather.wr
      usage: /<command>